<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 12px; color: #1a1a1a; line-height: 1.5; }

    .page { padding: 30px 35px; }

    /* Header */
    .header { display: table; width: 100%; border-bottom: 3px solid #2563eb; padding-bottom: 14px; margin-bottom: 16px; }
    .header-left { display: table-cell; vertical-align: middle; width: 60%; }
    .header-right { display: table-cell; vertical-align: middle; text-align: right; width: 40%; }
    .org-name { font-size: 18px; font-weight: bold; color: #1a1a1a; }
    .clinic-name { font-size: 15px; font-weight: bold; color: #2563eb; }
    .clinic-address { font-size: 10px; color: #6b7280; margin-top: 2px; }
    .clinic-phone { font-size: 10px; color: #6b7280; }

    /* Badge */
    .doc-badge { display: inline-block; background: #2563eb; color: #fff; padding: 3px 14px; border-radius: 14px; font-size: 10px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; margin-bottom: 12px; }

    /* Patient info box */
    .info-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 10px 14px; margin-bottom: 14px; }
    .info-grid { display: table; width: 100%; }
    .info-row { display: table-row; }
    .info-cell { display: table-cell; padding: 2px 8px 2px 0; font-size: 11px; width: 50%; }
    .info-label { font-weight: bold; color: #374151; }

    /* Section */
    .section { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 10px 14px; margin-bottom: 10px; }
    .section-title { font-size: 9px; text-transform: uppercase; color: #2563eb; letter-spacing: 0.8px; font-weight: bold; margin-bottom: 4px; }
    .section-content { font-size: 12px; color: #334155; }

    /* Table */
    .data-table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
    .data-table th { background: #f1f5f9; padding: 8px 10px; text-align: left; font-size: 10px; font-weight: bold; color: #374151; border-bottom: 2px solid #e2e8f0; }
    .data-table td { padding: 7px 10px; border-bottom: 1px solid #f1f5f9; font-size: 11px; }
    .data-table tr:last-child td { border-bottom: none; }
    .text-right { text-align: right; }
    .text-center { text-align: center; }
    .font-bold { font-weight: bold; }

    /* Footer */
    .footer { margin-top: 20px; display: table; width: 100%; }
    .footer-left { display: table-cell; vertical-align: bottom; font-size: 9px; color: #94a3b8; }
    .footer-right { display: table-cell; vertical-align: bottom; text-align: right; }
    .signature-box { border: 2px solid #333; display: inline-block; padding: 6px 14px; text-align: center; font-size: 11px; border-radius: 4px; }
    .signature-name { font-weight: bold; font-size: 12px; }
    .signature-detail { color: #555; font-size: 10px; }

    /* Watermark */
    .watermark { position: fixed; bottom: 10px; right: 35px; font-size: 8px; color: #d1d5db; }

    @yield('extra-styles')
</style>
</head>
<body>

<div class="page">

    {{-- Header --}}
    <div class="header">
        <div class="header-left">
            @if($org->logo_path ?? null)
                <img src="{{ public_path('storage/' . $org->logo_path) }}" style="max-height:40px;max-width:100px;margin-bottom:4px;"><br>
            @endif
            <div class="org-name">{{ $org->name ?? '' }}</div>
            @if($org->gst_number ?? null)
                <div style="font-size:9px;color:#6b7280;">GST: {{ $org->gst_number }}</div>
            @endif
        </div>
        <div class="header-right">
            <div class="clinic-name">{{ $clinic->name ?? '' }}</div>
            <div class="clinic-address">{{ $clinic->address ?? '' }}{{ $clinic->city ? ', ' . $clinic->city : '' }} {{ $clinic->pincode ?? '' }}</div>
            @if($clinic->phone ?? null)
                <div class="clinic-phone">Ph: {{ $clinic->phone }}</div>
            @endif
            @if($clinic->email ?? null)
                <div class="clinic-phone">{{ $clinic->email }}</div>
            @endif
        </div>
    </div>

    @yield('content')

</div>

<div class="watermark">Generated by ClinicDesq</div>

</body>
</html>
